# Generated by Django 4.2 on 2025-12-04 13:12

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_karyawan', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('no_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('manajer', 'Manajer / Pemilik'), ('staff_admin', 'Staff Administrasi'), ('staff_keuangan', 'Staff Keuangan'), ('lapangan', 'Staff Lapangan')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_layanan', models.CharField(max_length=30, unique=True)),
                ('nama_layanan', models.CharField(max_length=100)),
                ('harga_jasa', models.PositiveIntegerField(default=0)),
                ('estimasi_waktu', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pelanggan', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('no_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permohonan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_permohonan', models.CharField(max_length=30, unique=True)),
                ('status_proses', models.CharField(default='Menunggu Verifikasi', max_length=30)),
                ('biaya_resmi', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('metode_pengiriman', models.CharField(blank=True, max_length=30, null=True)),
                ('catatan_pelanggan', models.TextField(blank=True, null=True)),
                ('catatan_penolakan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_list', to='core.karyawan')),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.layanan')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permohonan_list', to='core.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(max_length=30, unique=True)),
                ('biaya_pengiriman', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_biaya', models.PositiveIntegerField(default=0)),
                ('metode_pembayaran', models.CharField(blank=True, max_length=30, null=True)),
                ('status_pembayaran', models.CharField(default='pending', max_length=30)),
                ('transaction_id_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permohonan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='core.permohonan')),
            ],
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_dokumen', models.CharField(max_length=30, unique=True)),
                ('path_file', models.FileField(max_length=255, upload_to=core.models.get_file_path)),
                ('status_file', models.CharField(default='Digital Diupload', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_dokumen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.masterdokumen')),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berkas_upload', to='core.permohonan')),
            ],
        ),
        migrations.CreateModel(
            name='LayananDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wajib', models.BooleanField(default=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syarat_dokumen', to='core.layanan')),
                ('master_dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterdokumen')),
            ],
            options={
                'unique_together': {('layanan', 'master_dokumen')},
            },
        ),
    ]
