# Generated by Django 4.2 on 2025-12-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermohonanAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Permohonan Dibuat'), ('verified', 'Diverifikasi'), ('rejected', 'Ditolak'), ('assigned', 'Ditugaskan ke Staff Lapangan'), ('in_progress', 'Sedang Diproses'), ('completed', 'Selesai Diproses'), ('delivered', 'Diserahkan ke Pelanggan')], max_length=50, verbose_name='Aksi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_logs', to='core.karyawan')),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.permohonan')),
            ],
            options={
                'verbose_name': 'Log Audit Permohonan',
                'verbose_name_plural': 'Log Audit Permohonan',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PembayaranAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invoice_created', 'Invoice Dibuat'), ('payment_verified', 'Pembayaran Diverifikasi'), ('payment_confirmed', 'Pembayaran Dikonfirmasi Lunas'), ('refund_processed', 'Refund Diproses')], max_length=50, verbose_name='Aksi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_logs', to='core.karyawan')),
                ('pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.pembayaran')),
            ],
            options={
                'verbose_name': 'Log Audit Pembayaran',
                'verbose_name_plural': 'Log Audit Pembayaran',
                'ordering': ['-timestamp'],
            },
        ),
    ]
