# Generated by Django 4.2.27 on 2026-01-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aktivitaslogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='catatan_perbaikan',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Perbaikan'),
        ),
    ]
