# Generated by Django 4.2.27 on 2026-01-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dokumen_catatan_perbaikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='bukti_pembayaran',
            field=models.FileField(blank=True, null=True, upload_to='bukti_bayar/'),
        ),
    ]
