# Generated by Django 4.2.27 on 2026-01-07 07:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pembayaran_bukti_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonan',
            name='hasil_lapangan',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models.get_file_path, verbose_name='Foto Hasil Dokumen'),
        ),
    ]
