# Generated by Django 4.2.27 on 2026-01-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_permohonan_hasil_lapangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonan',
            name='nomor_resi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomor Resi Pengiriman'),
        ),
    ]
