# Generated by Django 4.2.27 on 2026-01-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_permohonan_nomor_resi'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Layanan'),
        ),
        migrations.AddField(
            model_name='layanan',
            name='has_custom_tahapan',
            field=models.BooleanField(default=False, verbose_name='Gunakan Tahapan Kustom'),
        ),
        migrations.CreateModel(
            name='TahapanLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan Tahap')),
                ('nama_tahapan', models.CharField(max_length=100, verbose_name='Nama Tahapan')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('is_payment_required', models.BooleanField(default=False, verbose_name='Tahap Pembayaran?')),
                ('biaya_tahapan', models.PositiveIntegerField(default=0, verbose_name='Biaya Tahapan (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahapan_list', to='core.layanan')),
            ],
            options={
                'verbose_name': 'Tahapan Layanan',
                'verbose_name_plural': 'Tahapan Layanan',
                'ordering': ['urutan'],
                'unique_together': {('layanan', 'urutan')},
            },
        ),
        migrations.CreateModel(
            name='TahapanPermohonan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('in_progress', 'Sedang Diproses'), ('completed', 'Selesai'), ('skipped', 'Dilewati')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tahapan', to='core.permohonan')),
                ('tahapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_list', to='core.tahapanlayanan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tahapan_updates', to='core.karyawan')),
            ],
            options={
                'verbose_name': 'Progress Tahapan Permohonan',
                'verbose_name_plural': 'Progress Tahapan Permohonan',
                'ordering': ['tahapan__urutan'],
                'unique_together': {('permohonan', 'tahapan')},
            },
        ),
    ]
